logfile: "./logs/wegram.log"
loglevel: "debug"
ntfy_url: ""

service:
  port: 8088
  wxid: "wxid_xxxxx"
  baseurl: "http://127.0.0.1:8058/api"

ccy:
  saveimg_wxids:
    - "wxid_2sgby07xtcun22"
  img_time_range: [ '17:59:55','18:00:30' ]
  text_time_range: [ '18:00:00','18:01:30' ]
  weekdays:
    - 0
    - 2
    - 3
    - 6